import type { Task } from '@handoff/shared';

/**
 * Firestore エミュレータ無しでも UI 表示を確認できるローカル開発用シード。
 * created_by は null（特定ユーザーに紐づかない）だが、機械系作成タスクとして扱う。
 * ADR-0011 の OR フィルタ導入後は、意図的にサインイン後の人間ボードにも表示される。
 */
export const devSeed: Task[] = [
  {
    id: 'seed-1',
    title: '週次ニュースレターの下書き',
    status: 'needs-ai',
    owner: 'cowork',
    priority: 'P1',
    action_type: 'content',
    handoff_note: '先週の更新を3段落でまとめて',
    blocked_reason: null,
    tags: [],
    department: 'contents',
    role: 'brand-voice',
    project: 'ニュースレター',
    milestone: '6月号',
    created_by: null,
    created_by_type: 'machine',
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    activity: [{ timestamp: '2026-06-01T00:00:00Z', actor: 'human', action: 'created' }],
  },
  {
    id: 'seed-2',
    title: 'API 仕様レビュー',
    status: 'needs-human',
    owner: 'human',
    priority: 'P2',
    action_type: 'review',
    handoff_note: 'エンドポイント命名を確認してほしい',
    blocked_reason: null,
    tags: [],
    department: null,
    role: null,
    project: 'API刷新',
    milestone: 'v2',
    created_by: null,
    created_by_type: 'machine',
    created_at: '2026-06-01T01:00:00Z',
    updated_at: '2026-06-01T01:00:00Z',
    activity: [{ timestamp: '2026-06-01T01:00:00Z', actor: 'human', action: 'created' }],
  },
  {
    id: 'seed-3',
    title: '競合調査メモの統合',
    status: 'in-progress',
    owner: 'claude-code',
    priority: 'P2',
    action_type: 'research',
    handoff_note: '3社分を1ページに',
    blocked_reason: null,
    tags: [],
    department: 'business',
    role: 'business-strategy',
    project: '競合調査',
    milestone: null,
    created_by: null,
    created_by_type: 'machine',
    created_at: '2026-06-01T02:00:00Z',
    updated_at: '2026-06-01T03:00:00Z',
    activity: [{ timestamp: '2026-06-01T02:00:00Z', actor: 'human', action: 'created' }],
  },
];
